using Application.Solver.Days;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Application.Tests.Solver.Days;

[TestClass]
public class SolutionDay08Test : SolutionDay08
{
    private const string Input = """
                                 ............
                                 ........0...
                                 .....0......
                                 .......0....
                                 ....0.......
                                 ......A.....
                                 ............
                                 ............
                                 ........A...
                                 .........A..
                                 ............
                                 ............
                                 """;

    private const int Part1Expected = 14;

    [TestMethod]
    public void ResolvePart1Test() => new SolutionDay08().Resolve(1, Input).Should().Be(Part1Expected);

    private const int Part2Expected = 34;

    [TestMethod]
    public void ResolvePart2Test() => new SolutionDay08().Resolve(2, Input).Should().Be(Part2Expected);
}